### ISSUE TITLE
Autofac ASP.NET MVC 5 Integration cannot install

### ISSUE THREAD

**Issue by TJHan** [autofac/Autofac.Mvc#12]
Hey,
I can not install Autofac ASP.NET MVC 5 Integration successful on my pc,
my local environment is:
 VS Pro 2013, Update 5
MVC project is .net framework 4.5, MVC 5.2.3.
I was installed AutoFac first, and then trying to install Autofac ASP.NET MVC 5 Integration, but failed.
Error message is chinese, i'm trying to translate it as below:
You are trying to install this package to a will ". Netframework, version = 4.5 "as the target of the project, But this package does not contain any compatible with the framework of the assembly references or content files.

**Comment by alexmg** [comment]
Try bumping your project up to .NET 4.5.1. I'll take a look at pushing that requirement down to 4.5. I have a feeling we had to push it up to 4.5.1 at one point because of another issue. If that's resolved the dependency will be lowered in the next point release.

**Comment by tillig** [comment]
Keep in mind [support for .NET 4.5 and 4.5.1 has actually officially ended](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/). I might recommend bumping your project up to .NET 4.5.2 if you can to get on an MS supported codeline.

**Comment by TJHan** [comment]
oh thx, Project up to .NET 4.5.1, it's work.
