### ISSUE TITLE
how can i implement autofac on mvc 5.2 and 4.5.2 framework ?

### ISSUE THREAD

**Issue by ghost** [autofac/Autofac.Mvc#13]
In this page :https://www.nuget.org/packages/Autofac.Mvc5/
In Discription told :

> Dependencies
> Autofac (>= 4.0.0 && < 5.0.0)
> Microsoft.AspNet.Mvc (>= 5.1.0 && < 6.0.0)
> 
> and Updated to .NET 4.5.1, Autofac 4 compatibility

in my project i used mvc 5.2 and dot net 4.5.2

how can implement Autofac on my project ?

Quick Start MVC (this page : http://autofac.readthedocs.io/en/latest/integration/mvc.html#quick-start)

> told 
> 
> ```
>   // Register your MVC controllers.
>   builder.RegisterControllers(typeof(MvcApplication).Assembly);
> ```

but in my project get an error "Could not be found"

how can fix it ?

**Comment by tillig** [comment]
[This question appears to be cross-posted to StackOverflow.](http://stackoverflow.com/q/39817033/8116) Answers from us and/or the community will be there.
