### ISSUE TITLE
Add .NET Framework 4.5 support to packaging

### ISSUE THREAD

**Issue by mwpowellhtx** [autofac/Autofac.Mvc#15]
I tested locally and repackaged. Seems to work just fine. I can post a PR for the nuspec if you prefer.

May need to rinse and repeat for Autofac.Mvc.Owin or other packages along similar lines.

Thank you...

**Comment by tillig** [comment]
A PR would be awesome.

**Comment by mwpowellhtx** [comment]
Okay, I may have spoken too soon.

Packaging is straightforward enough, but the DLL is built against ``.NET Framework 4.5.1``. As long as my host assembly is targeting the same it is fine, but when it targets ``4.5``, not so much. Shows up as a warning, but blocks the runtime, so it's more like an error.

Is it possible for you to also target ``4.5``, or is that asking too much?

I'm open to suggestions, but I seem to recall having problems with the .NET Frameworks ``4.5.X`` and ``4.6.X`` upgrade paths a little while back.  Not sure if those issues have been resolved and we're clear to proceed.

**Comment by alexmg** [comment]
I have pushed new packages to MyGet that target .NET Framework 4.5.

- Autofac.Mvc5 - 4.0.1-CI-235
- Autofac.Mvc5.Owin - 4.0.1-CI-222

@mwpowellhtx It would be great if you could give these a test run from the MyGet feed below. If all goes well I will push them over to NuGet as release packages.

https://www.myget.org/F/autofac/api/v2/

**Comment by mwpowellhtx** [comment]
@alexmg Hello and thanks for the follow up on this one. As it happens I am wrapping up another development cycle on the libraries that are using these reference(s), so... I can't promise exactly when, but before I dot my i's and cross my t's I will response with feedback.

**Comment by mwpowellhtx** [comment]
@alexmg Okay, I added the package source, and I am trying to find it in via the VS2015 package manager. However, I do not see it, even under the pre-released packages. Are you sure that you increased the version number(s)?

_Edit_: At least a build number change I would think; i.e. from *1.2.3* to *1.2.4*.

Thanks!

**Comment by mwpowellhtx** [comment]
@alexmg Following up on this. Any movement towards increasing the version number(s)? Thanks!

**Comment by mwpowellhtx** [comment]
@alexmg Sorry didn't see the versions. I happened to have named my local package 4.0.1, so it wasn't showing up. I saw it as a "side grade", so I installed the CI package. Seems to build and run fine, thanks.

**Comment by alexmg** [comment]
Great. I'll push the new packages over to NuGet a bit later today.

**Comment by alexmg** [comment]
I've pushed the two packages over to NuGet as release packages.
