### ISSUE TITLE
Different resolving from constructor injection and DependencyResolver.Current.GetService

### ISSUE THREAD

**Issue by DmitryProskurin** [autofac/Autofac.Mvc#18]
Hello evryone. I have a question about this two types of resolving.
(Autofac 4.4.0 // Autofac.Mvc5 4.0.1 // Autofac.WebApi2 // 4.0.1)
I have interface
```
public interface IUserContext
{
	User User { get; set; }
}
```
I register it with ContainerBuilder:
```
var builder = new ContainerBuilder();
builder.RegisterControllers(typeof(BaseController).Assembly);
builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
builder.RegisterType<UserContext>().As<IUserContext>().InstancePerRequest();
builder.RegisterType<TaxAuditLogicToTableViewModelConverter>().AsSelf().InstancePerRequest();
var container = builder.Build();
DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(container);
```
So, i have authorization attribute. In attribute i resolve another service(`DependencyResolver.Current.GetService<IAuthorization>()`), in implementation of IAuthorization, IUserContext pass as contructor parameter and set User field.
I'll try get IUserContext two ways:
```	
class FinalStepLogicToViewConverter : ITypeConverter<TaxAudit, LastStepViewModel>
{
	public FinalStepLogicToViewConverter(IUserContext uc)
	{
		var nullReference = uc.User;//thats null
		var notNullReference = DependencyResolver.Current.GetService<IUserContext>().User;//thats not null
	}
}
//FinalStepLogicToViewConverter need me for using in automapper:
...
CreateMap<X, Y>().ConvertUsing<FinalStepLogicToViewConverter>();
...
```
Why in one case it's null, and not null in another? How can i solve this without direct call dependecy resolver?

**Comment by tillig** [comment]
This sort of question is great to ask over at [StackOverflow](http://stackoverflow.com). We project owners monitor that, but you also get _a great community_ of additional people that can chip in. It will get you an answer much faster.

If you decide to ask there -

- Tag it `autofac` along with your other tags
- Add some clarification to the question - you have MVC and Web API in one project. Is the attribute in question a Web API or MVC attribute? Can we see the code? Can we see where it's used?
- Add a link to the question here and we'll close the issue. We'd answer over there.

**Comment by tillig** [comment]
We actually do need the clarification on whether this is a Web API or MVC attribute, with the additional code, etc. regardless of whether you ask on StackOverflow or not... but since SO is your best bet, I'm going to close this issue and you can retroactively add the link to your question when you get a chance to ask it over there.
