### ISSUE TITLE
The presence of concurrency issues

### ISSUE THREAD

**Issue by xLabel** [autofac/Autofac.Mvc#19]
concurrency  to new more instances of RequestLifetimeScopeProvider

that will case Some concurrent object will not be released in "concurrent RequestLifetimeScopeProvider "lifetimescope ??

AutofacDependencyResolver.cs
![222](https://cloud.githubusercontent.com/assets/3363613/24771333/d48103cc-1b3f-11e7-984e-e6153143d3e8.jpg)

**Comment by tillig** [comment]
Have you actually encountered this or is it hypothetical?

**Comment by xLabel** [comment]
Thank you for your reply!
 : )

sorry, only hypothetical. Yesterday was too tired to work, did not really see clearly.

And now  I already understand this.

"RequestLifetimeScopeProvider" will new() more than one instance when concurrency occur ,
But ultimately will not affect the release of the LifetimeScope 
because the LifetimeScope reference every httpcontext.

My understanding right?

RequestLifetimeScopeProvider.cs
![111](https://cloud.githubusercontent.com/assets/3363613/24786044/0522107e-1b91-11e7-8f05-448239bbb0b9.jpg)
