### ISSUE TITLE
Could not load file or assembly 'System.Web.Mvc, Version=5.1.0.0

### ISSUE THREAD

**Issue by eman1986** [autofac/Autofac.Mvc#22]
I recently updated my System.Web.Mvc to 5.2.3.0 and now the MVC 5 library is throwing the following error:

> Could not load file or assembly 'System.Web.Mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

If I uncomment the autofac stuff it sorta works (it gripes about missing autofac but figured that'd happen)

**Comment by tillig** [comment]
Sounds like you're missing an assembly binding redirect in your web.config file. Usually NuGet handles that, sounds like it got missed. [See Microsoft doc.](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions)

**Comment by eman1986** [comment]
I have System.Web.Mvc set up

`            <dependentAssembly>
                <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35"/>
                <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0"/>
            </dependentAssembly>`

but looking at your source, it's using 5.1.0.0

**Comment by tillig** [comment]
Correct. The assembly binding redirect will tell your app at runtime to stop looking for 5.1.0 and look for 5.2.3. That's the whole point of assembly binding redirects - we maintain backwards compatibility and support for an older version but you can upgrade your application's specific version to the new one and it should still work.
