### ISSUE TITLE
Project still under active development?

### ISSUE THREAD

**Issue by djluck** [autofac/Autofac.Mvc#23]
I've identified a couple of performance issues with how the Autofac MVC library injects filters and parameter values which I'd like to try and address. Before I spend time creating and submitting a PR I'd like to know- will it be considered and if it meets the projects standards, merged?

**Comment by alexmg** [comment]
We are always open to improvements. Given the integration is currently stable we would not likely consider breaking changes though. Do the optimisations you have in mind require breaking changes?

**Comment by djluck** [comment]
Thanks for the quick reply Alex. No, I hadn't planned on making any
breaking changes and I will certainly keep this in mind.

**Comment by tillig** [comment]
Doesn't look like there's anything else here to discuss so I'm going to close this. If there are enhancements desired, it'd be good to file an issue to describe the problem prior to jumping into PR/coding just to make sure there's not something else going on.
