### ISSUE TITLE
can name injection be supported

### ISSUE THREAD

**Issue by softlgl** [autofac/Autofac.Mvc#31]
If multiple instances implement the same interface and multiple names are registered at the time of registration, can name be used to distinguish one implementation of the injected interface in the injected concrete implementation class

**Comment by tillig** [comment]
I think what you're looking for is [the `KeyFilterAttribute`](https://autofac.readthedocs.io/en/latest/advanced/metadata.html#keyfilterattribute), which isn't specifically tied to MVC support.

If that's not it, we need a lot more here to understand the request, like maybe a small code snippet with something showing what you're trying to do but which isn't working.
