### ISSUE TITLE
Compatibility with Autofac v6

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac.Mvc#34]
v6 Compatibility and version dependency checks ahead of release.

**Comment by alistairjevans** [comment]
Since we took the CLS Compliant attribute out of the main Autofac package, I'm now getting CLS Compliance warnings throughout this integration. 

Is this going to be an issue? Do we need to put the CLS Compliant flag back in Autofac?

**Comment by tillig** [comment]
Autofac isn't actually CLS compliant, I don't think. I forget what it was exactly that started failing.

I'd be OK with removing the CLS compliant flag from this integration if we can't put it back on core Autofac.

**Comment by alistairjevans** [comment]
DiagnosticSource isn't CLS Compliant, hence Autofac can't be either; interestingly none of the .NET Core libraries are now, so it feels like CLS compliant is less useful nowadays anyhow.
