### ISSUE TITLE
Appveyor not pushing packages

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac.Mvc#38]
For some reason, Appveyor isn't pushing packages for this repo's builds.

NuGet file is created, but appveyor just says "No packages were pushed"

See example: https://ci.appveyor.com/project/Autofac/autofac-mvc/builds/35452792

It appears to have been doing this since the previous release (I guess when we changed to the new build approach?)

@tillig, you seen this before?

**Comment by tillig** [comment]
Looks like a little bit of the `appveyor.yml` was missing - the definition of where artifacts are and then tying that to the publish step. I added those in and it's publishing again. I'll get this released.
